# Generated by Django 3.1.13 on 2022-03-31 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_password', models.CharField(max_length=20)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_address', models.CharField(max_length=500)),
                ('user_cards', models.CharField(max_length=20)),
                ('user_numbers', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('create_date', models.DateField()),
                ('age', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=20)),
            ],
        ),
    ]
